### ISSUE TITLE
CS50 module prevents ability to import local python files

### ISSUE THREAD

**Issue by Filip62** [cs50/python-cs50#107]
**### _Note: This does not happen on CS50 Web IDE._**
**### _Note: I was using VSCode on my PC._**
**### _Note: It is not necessarily an issue, but I think you should definitely point it out in the course._**

While working on **pset7 from CS50 on edX**,

In the application.py, if I imported the CS50 module before I import the functions in _helpers.py_,
which is located in the same directory as _application.py_.

**application.py:**
```python
import cs50
import re
from flask import Flask, abort, redirect, render_template, request
from html import escape
from werkzeug.exceptions import default_exceptions, HTTPException

from helpers import lines, sentences, substrings
```

Then I get this error:

``` 
Traceback (most recent call last):
  File "/home/filip/Web/Workspace/similarities/application.py", line 7, in <module>
    from helpers import lines, sentences, substrings
ModuleNotFoundError: No module named 'helpers'
```
But if I move the 
```python
import cs50
```  
below 
```python
from helpers import lines, sentences, substrings
``` 
or if I move the
```python
from helpers import lines, sentences, substrings
``` 
above the 
```python
import cs50
```  
statement,

**Modified application.py:**
```python
import re
from flask import Flask, abort, redirect, render_template, request
from html import escape
from werkzeug.exceptions import default_exceptions, HTTPException

from helpers import lines, sentences, substrings

import cs50
```
then everything works fine, because the CS50 module erases the local directory from sys.path from which apllication.py was ran after the local helpers import is done.

**Comment by dmalan** [comment]
Thanks for catching this, @Filip62! We'll roll out a fix soon!

**Comment by dmalan** [comment]
https://github.com/cs50/python-cs50/commit/738a14dda1664e109064193614c75b99591e90e0
