### ISSUE TITLE
Error while deploying to Heroku

### ISSUE THREAD

**Issue by aargar1** [cs50/python-cs50#143]
I cannot delpoy for heroku. I get the following output.

`ERROR: Could not find a version that satisfies the requirement apsw==3.28.0.post1 (from -r /tmp/build_d26e4ecc/requirements.txt (line 4)) (from versions: 3.8.2.post1, 3.8.5.post1, 3.8.6.post1, 3.8.7.1.post1, 3.8.7.2.post1, 3.8.7.3.post1, 3.8.8.1.post1, 3.8.8.2.post1, 3.8.9.post1, 3.8.10.1.post1, 3.8.11.1.post1, 3.9.2.post1)
remote:        
ERROR: No matching distribution found for apsw==3.28.0.post1 (from -r /tmp/build_d26e4ecc/requirements.txt (line 4))`

Why is this so? How to fix this?

**Comment by dmalan** [comment]
Afraid this doesn't seem to be an issue with `python-cs50`? Looks like you're trying to use an unsupported version of `apsw`. If `python-cs50` is indeed the source of the issue, do show us the entirety of `requirements.txt`!

**Comment by aargar1** [comment]
Here's requirements.txt:

a-pytube-fork-for-spotdl-users==9.6.4
acme==1.1.0
appdirs==1.4.3
apsw==3.28.0.post1
arcade==2.5.1
asgiref==3.3.1
attrs==20.3.0
autopep8==1.5.4
backports.shutil-get-terminal-size==1.0.0
backports.shutil-which==3.5.2
beautifulsoup4==4.8.2
blinker==1.4
braceexpand==0.1.6
breezy==3.0.2
Brlapi==0.7.0
cachelib==0.1.1
caffeine==2.9.4
cairocffi==1.2.0
CairoSVG==2.5.0
certbot==0.40.0
certifi==2019.11.28
cffi==1.14.4
chardet==3.0.4
check50==3.2.0
chrome-gnome-shell==0.0.0
cli50==4.0.0
click==7.1.2
colorama==0.4.3
command-not-found==0.3
compare50==1.2.2
ConfigArgParse==0.13.0
configobj==5.0.6
cryptography==2.8
cs50==5.1.0
css-parser==1.0.4
cssselect==1.1.0
cssselect2==0.4.1
cssutils==1.0.2
cupshelpers==1.0
dbus-python==1.2.16
defer==1.0.6
defusedxml==0.6.0
Deprecated==1.2.7
distlib==0.3.0
distro==1.4.0
distro-info===0.23ubuntu1
Django==3.1.4
dnspython==1.16.0
docopt==0.6.2
dulwich==0.19.15
EditorConfig==0.12.2
entrypoints==0.3
evdev==1.3.0
ewmh==0.1.6
fastimport==0.9.8
feedparser==5.2.1
filelock==3.0.12
Flask==1.1.2
Flask-Session==0.3.2
future==0.18.2
gpg===1.13.1-unknown
hidpidaemon==18.4.6
html2text==2020.1.16
html5-parser==0.4.9
html5lib==1.0.1
httplib2==0.14.0
icdiff==1.9.1
idna==2.8
ifaddr==0.1.6
importlib-metadata==1.5.0
inflect==5.0.2
intervaltree==2.1.0
itsdangerous==1.1.0
jellyfish==0.8.2
Jinja2==2.11.2
josepy==1.2.0
jsbeautifier==1.13.0
keyring==18.0.1
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
lib50==2.0.9
libvirt-python==6.1.0
louis==3.12.0
lxml==4.5.0
macaroonbakery==1.3.1
Markdown==3.1.1
MarkupSafe==1.1.1
mechanize==0.4.5
mock==3.0.5
more-itertools==4.2.0
msgpack==0.6.2
mutagen==1.45.1
natsort==7.1.0
netifaces==0.10.4
nose==1.3.7
numpy==1.19.2
oauthlib==3.1.0
olefile==0.46
packaging==20.3
parsedatetime==2.4
pbr==5.4.5
pexpect==4.8.0
Pillow==8.0.1
pop-transition==1.0.1
protobuf==3.6.1
protonvpn-cli==2.2.6
psutil==5.5.1
ptyprocess==0.6.0
pycairo==1.16.2
pychm==0.8.6
pycodestyle==2.6.0
pycparser==2.20
pycrypto==2.6.1
pycups==1.9.73
pydbus==0.6.0
pyflatpak==0.4.0
PyGithub==1.43.7
pyglet==1.5.11
Pygments==2.7.3
PyGObject==3.36.0
PyICU==2.4.2
PyJWT==1.7.1
pymacaroons==0.13.0
pymunk==5.7.0
PyNaCl==1.3.0
pyOpenSSL==19.0.0
pyparsing==2.4.6
PyPDF2==1.26.0
Pyphen==0.10.0
PyQt5==5.14.1
PyQtWebEngine==5.14.0
pyRFC3339==1.1
python-apt===2.1.2pop0-1587756471-20.04-cd2988e
python-dateutil==2.7.3
python-debian===0.1.36ubuntu1
python-gitlab==2.0.1
python-magic==0.4.18
python-xlib==0.23
pythondialog==3.5.1
pytiled-parser==0.9.4a3
pytube @ git+https://github.com/nficano/pytube@0bd6673906cea543bcdd72de9da05e2a14b74d34
pytz==2019.3
pyudev==0.21.0
pyxdg==0.26
PyYAML==5.3.1
qrcode==6.1
rapidfuzz==0.14.1
regex==2019.8.19
render50==4.2.1
repoman==1.2.2
reportlab==3.5.56
repoze.lru==0.7
requests==2.22.0
requests-toolbelt==0.8.0
requests-unixsocket==0.2.0
Routes==2.4.1
SecretStorage==2.3.1
sessioninstaller==0.0.0
setproctitle==1.1.10
Shapely==1.7.1
simplejson==3.16.0
sip==4.19.21
six==1.14.0
sortedcontainers==2.3.0
soupsieve==1.9.5
spotdl==3.1.4
spotipy==2.16.1
SQLAlchemy==1.3.19
sqlparse==0.3.1
style50==2.7.4
submit50==3.0.2
systemd-python==234
termcolor==1.1.0
tinycss2==1.1.0
toml==0.10.2
tqdm==4.54.1
typing-extensions==3.7.4.3
ubuntu-advantage-tools==20.3
ubuntu-drivers-common==0.0.0
ufw==0.36
urllib3==1.25.8
virtualenv==20.0.17
wadllib==1.3.3
WeasyPrint==52.2
webencodings==0.5.1
WebOb==1.8.5
Werkzeug==1.0.1
wrapt==1.11.2
xkit==0.0.0
zeroconf==0.24.4
zipp==1.0.0
zope.component==4.3.0
zope.event==4.4
zope.hookable==5.0.0
zope.interface==4.7.1`
`

**Comment by dmalan** [comment]
Afraid that error seems unrelated to `cs50`!
