### ISSUE TITLE
PIP3 install cs50 no longer works

### ISSUE THREAD

**Issue by avipars** [cs50/python-cs50#144]
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/cs50/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/cs50/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/cs50/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/cs50/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/cs50/
ERROR: Could not find a version that satisfies the requirement cs50 (from versions: none)
ERROR: No matching distribution found for cs50

This is on ubuntu 20 , any solutions?

**Comment by dmalan** [comment]
Sounds like a transient PyPi issue! Best to try again!

**Comment by avipars** [comment]
Thanks, if I wanted to build it locally or run the project... can i just download the source code and place it in the project ?
