### ISSUE TITLE
large inputs not handled

### ISSUE THREAD

**Issue by MuhammadHassanRazaa** [cs50/python-cs50#145]
get_string() and get_int() are not accepting large input (i.e. 2048 bits)

**Comment by kzidane** [comment]
Can you please be more specific? What steps did you take to reproduce this problem?

**Comment by MuhammadHassanRazaa** [comment]
when i pasted the following number in the input to the command ``` a = get_int('long number')```, the number gets truncated to 1/3rd while inputting. here's the video [link](https://youtu.be/X0aFxQryvj4).
![image](https://user-images.githubusercontent.com/47544114/110510896-f037b600-8103-11eb-93a0-d41d14baa82f.png)

**Comment by MuhammadHassanRazaa** [comment]
@dmalan it can't be ```cmd.exe``` limitation. The character count of my input is just 1233, but according to the link you've specified cmd can take 8191 characters once. 

Secondly, if it's a cmd limitation, the built-in python ```input()``` function shouldn't work.

Looking forward :)

Regards

**Comment by dmalan** [comment]
Ah, apologies, quite right, I'm seeing a 4096-char limit on Linux. We'll take a look!

**Comment by MuhammadHassanRazaa** [comment]
No problem, btw I've seen the source code, you guys have used sys.stdin.readline to take input, maybe there's some limitation of this function, changing it to input() may resolve the problem.

But I've tested the same code on repl.it, get_int() worked perfectly there.

That's why I am confused, maybe there's some limitation of windows and Linux operating system or something else.

Regards

________________________________

**Comment by kzidane** [comment]
Should be fixed in #147.

**Comment by dmalan** [comment]
Thanks for reporting, @MuhammadHassanRazaa! There may still be platform-specific limitations, though, just fyi!

**Comment by MuhammadHassanRazaa** [comment]
You're Welcome @dmalan 👍 :).  I have tested this code on Kali Linux, Parrot, Windows(cmd and PowerShell) and Ubuntu, it is working perfectly with characters allowed in the respective shell.  

Thank you for making the correction :)
