### ISSUE TITLE
db.execute() returning KeyError when using one keyword argument twice

### ISSUE THREAD

**Issue by Raghav1999** [cs50/python-cs50#159]
below is the example of SQL query which produces KeyError:
db.execute("SELECT col1,col2 FROM table WHERE col3=:email AND col4=:email AND col5=:dob", email=email, dob=dob)

Here, the same keyword argument :email is used twice in the query but it raises KeyError in **cs50 7.0.1** but it was working fine previously.

Using '?' positional arguments works fine.

![OutputAfterSQL_Query](https://user-images.githubusercontent.com/36398524/127293645-5f9df2f7-6eb2-4049-9942-037eb1db6a0b.png)

**Comment by kzidane** [comment]
Good catch! Should be fixed in 7.0.2. Thank you.
