### ISSUE TITLE
pyttsx3 - OS error libespeak.so.1: cannot open shared object file : No such file or directory

### ISSUE THREAD

**Issue by sujithauday** [cs50/python-cs50#169]
After installing pyttsx3 in code.cs50.io

- pip install pyttsx3 
successfully installed pyttsx3-2.90
 used the following code :

import pyttsx3

engine = pyttsx3.init()
engine.say("Hello CS50")
engine.rundAndWait()

Getting exception:
Key Error : None
OSError : libespeak.so.1: cannot open shared object file: No such file or directory

Tried couple of solution from online but couldn't resolve.

**Comment by dmalan** [comment]
Afraid audio won't work in Codespaces!

**Comment by sujithauday** [comment]
I'm trying to use it as a feature in my final project for "CS50's Introduction to Programming with Python ".  
Pyttsx3 library was used in the class Et Cetera session.

**Comment by balajiabhinav5** [comment]
yes same here

for me also it is not working, but for David J. Malan it works

**Comment by rongxin-liu** [comment]
> yes same here
> 
> for me also it is not working, but for David J. Malan it works

Hi, pyttsx3 won't work on Codespae. Prof. Malan was demoing that through his macOS terminal.
