### ISSUE TITLE
Does not work with sqlalchemy-2.0.21

### ISSUE THREAD

**Issue by anxkhn** [cs50/python-cs50#177]
CS50 python package cs50-9.2.6, still has SQLAlchemy-1.4.46 as a dependency.
Update it to work with sqlalchemy-2.0.21 as it is newer and is required for langchain and llama_index.

**Comment by rongxin-liu** [comment]
We do have a PR up already to address this:
https://github.com/cs50/python-cs50/pull/174

We will merge once it is safe for us to do so.

**Comment by rongxin-liu** [comment]
[https://github.com/cs50/python-cs50/commit/fcc8cb9ff196cf66f5867f70d22a27994b6b4073](https://github.com/cs50/python-cs50/commit/fcc8cb9ff196cf66f5867f70d22a27994b6b4073)
