### ISSUE TITLE
how to submit my code ?

### ISSUE THREAD

**Issue by engaboud** [cs50/python-cs50#184]
how to submit my code ?
![error](https://user-images.githubusercontent.com/86140283/123575136-c3142e00-d7ee-11eb-8b02-38c7d9c52d26.png)

_Originally posted by @sidratil in https://github.com/cs50/submit50/issues/251#issuecomment-869322629_

**Comment by dmalan** [comment]
Best to email sysadmins@cs50.harvard.edu!

**Comment by engaboud** [comment]
Of course, my distinguished professor
You have completed all the lessons in this course

في الأربعاء، ١٧ يوليو ٢٠٢٤, ٢:١٨ ص David J. Malan ***@***.***>
كتب:
