### ISSUE TITLE
Missing "install" make rule

### ISSUE THREAD

**Issue by knifecake** [cs50/python-cs50#2]
Trying to follow instructions to install lib50-python on macOS Sierra (per the README) I encountered the following error:

```
$ make install
make: *** No rule to make target `install'.  Stop.
```

I cannot see an easy way to implement this myself (it does not seem easy to get the user's `$PYTHONPATH`. And even if we got it and we could move the file to that directory, would it be too much code to put on a `Makefile`?) 

Is there any chance this module could be made available through `pip install cs50`? Or maybe it is better to provide some instructions on how access the module by placing `cs50.py` on the same directory as the main file?

**Comment by ehzShelter** [comment]
issue #3 may help you ...

**Comment by knifecake** [comment]
See #3 for a pip package.
