### ISSUE TITLE
No pip package for new cs50 library 2016

### ISSUE THREAD

**Issue by ehzShelter** [cs50/python-cs50#3]
**"pip install cs50"** is installing this one >> _https://pypi.python.org/pypi/CS50/0.2_

Here makefile is working though due to docker or something else

Anyway, My problem is resolved by copying all .py src files to my locally installed python3.6
mkdir ~/.myPython/lib/python3.6/site-packages/cs50
cp src/* ~/.myPython/lib/python3.6/site-packages/cs50/
[ /usr/lib/python3/dist-packages/cs50 for situation It varies ] 

But one dependency is needed for sql.py that **SQLALchemy**
**pip install SQLAlchemy**

**Comment by dmalan** [comment]
PyPi has been updated, so `pip install cs50` and `pip3 install cs50` should now work for the latest verison of the library!

CC @kzidane

**Comment by ehzShelter** [comment]
Cool :+1:
