### ISSUE TITLE
input uses original stdout

### ISSUE THREAD

**Issue by kzidane** [cs50/python-cs50#54]
Per https://bugs.python.org/issue28373, `input` uses original stdout even if `sys.stdout` is wrapped. When students use `input` and pass in a prompt, stdout buffering is enabled for this even if they import the `cs50` module. 

One suggested workaround is to override the `fileno` method but not sure how reliable that is:

```
import cs50
input("foo") # doesn't use the overridden write method
```

```
import cs50
cs50.get_int("foo") # uses the overridden write method
```

**Comment by dmalan** [comment]
@crossroads1112 any thoughts?

**Comment by dmalan** [comment]
https://github.com/cs50/python-cs50/commit/df79b1189fbebeecb800e3f2761ce61051155c89
