### ISSUE TITLE
some exceptions in Flask aren't colorized by our monkey-patching

### ISSUE THREAD

**Issue by dmalan** [cs50/python-cs50#61]
1. Copy https://gist.github.com/dmalan/14ed9ec6548df079ea4468f435c7dc6b into a directory.
1. Run `pip3 install -r requirements.txt`.
1. Run `flask run`.
1. Visit `/foo`, and you should see that traceback is highlighted by CS50 library: lines that aren't in site-packages are highlighted in yellow.
1. Visit `/bar`, and you should see that traceback isn't highlighted.

The lack of highlighting in the last step appears to be the result of https://github.com/pallets/werkzeug/blob/master/werkzeug/serving.py#L284-L295, whereby the traceback being printed at that point in the app's lifecycle is coming from `werkzeug.debug.tbtools.get_current_traceback`, specifically `traceback.plaintext`. Would be ideal to format `traceback.plaintext` using https://github.com/cs50/python-cs50/blob/develop/src/cs50/cs50.py#L68 as well, though currently our function's signature expects `(type, value, tb)`. 

Perhaps simplest to monkey-patch `werkzeug.debug.tbtools.get_current_traceback` in https://github.com/cs50/python-cs50/blob/develop/src/cs50/flask.py, just as we do `flask.logging.default_handler.formatter.formatException`? Or monkey-patch the `Traceback.plaintext` property instead, https://github.com/pallets/werkzeug/blob/master/werkzeug/debug/tbtools.py#L379?

**Comment by crossroads1112** [comment]
I mentioned this in our Slack discussion but I'll add it here too. `SyntaxErrors` occur before any code is executed, so I don't believe that anything we put in the library can fix this (since the error is thrown before any of our library code is executed). I think the only solution to this would be to write a wrapper around `flask run` I know we currently have a shell wrapper, but I mean a Python one that can do this patching.

**Comment by dmalan** [comment]
Those `SyntaxError`s are being caught and printed by https://github.com/pallets/werkzeug/blob/master/werkzeug/serving.py#L284-L295, though? So we should be able to hook into werkzeug's code, no?

**Comment by dmalan** [comment]
Ah, gotcha, I worry I chose a bad example. Pretty sure the lack of highlighting reared its head for a student in another context; my introduction of the syntax error was just meant to distill their code into something simpler that would still raise an exception, but clearly a red herring. Will try to resurrect the actual symptom.
